server:
  port: 8084

spring:
  application:
    name: voucher-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/yafd_vouchers}
    username: ${DB_USERNAME:yafd}
    password: ${DB_PASSWORD:yafd_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
