server:
  port: 8084

spring:
  application:
    name: voucher-service
  datasource:
    url: jdbc:postgresql://localhost:5432/yafd_vouchers
    username: yafd
    password: yafd_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
